import nock from 'nock'
import { config } from '../../app/config.js'
import { generateKeyPairSync } from 'node:crypto'
import jwt from 'jsonwebtoken'

const { publicKey, privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048 })
const DEFRA_ID_KID = 'mock-defra-id-key-id'

/**
 * Generates a (locally) signed defra id token, that can be verified within the DAL
 */
export const signDefraIdToken = (payload) =>
  jwt.sign(payload, privateKey, { algorithm: 'RS256', keyid: DEFRA_ID_KID })

/**
 * Mocks the Defra ID well known configuration and jwks_uri lookups so that a token
 * generated by signDefraIdToken above can be verified
 */
export const mockDefraIdJwks = () => {
  const wellKnownUrl = new URL(config.get('defraId.wellKnownUrl'))
  const jwksUri = `${wellKnownUrl.origin}/discovery/v2.0/keys`
  const scope = nock(wellKnownUrl.origin)

  scope.get(wellKnownUrl.pathname).reply(200, { jwks_uri: jwksUri })
  scope.get('/discovery/v2.0/keys').reply(200, {
    keys: [
      {
        kty: 'RSA',
        kid: DEFRA_ID_KID,
        alg: 'RS256',
        use: 'sig',
        n: publicKey.export({ format: 'jwk' }).n,
        e: publicKey.export({ format: 'jwk' }).e
      }
    ]
  })
}

export const mockOrganisationSearch = (nockInstance, orgId = 'organisationId') => {
  nockInstance
    .post('/organisation/search', {
      searchFieldType: 'SBI',
      primarySearchPhrase: '123456789',
      offset: 0,
      limit: 1
    })
    .reply(200, {
      _data: [
        {
          id: orgId
        }
      ]
    })
}

export const mockPersonSearch = (nockInstance, crn = '1234567890') => {
  nockInstance
    .post('/person/search', {
      searchFieldType: 'CUSTOMER_REFERENCE',
      primarySearchPhrase: crn,
      offset: 0,
      limit: 1
    })
    .reply(200, {
      _data: [
        {
          id: 'personId'
        }
      ]
    })
}
