type Query {
  business(sbi: ID!): Business
  businessSearch(
    searchString: String!
    searchType: BusinessSearchFieldType!
    pagination: Pagination
  ): BusinessSearchResponse
  customer(crn: ID!): Customer
  customerSearch(
    searchString: String!
    searchType: CustomerSearchFieldType!
    pagination: Pagination
  ): CustomerSearchResponse
  permissionGroups: [PermissionGroup]
}

type Mutation {
  createBusinessCustomerBankDetails(
    input: CreateBusinessCustomerBankDetailsInput!
  ): CreateBusinessCustomerBankDetailsResult
}

type Phone {
  mobile: String
  landline: String
}

type Email {
  address: String
  validated: Boolean
}

type Address {
  pafOrganisationName: String
  line1: String
  line2: String
  line3: String
  line4: String
  line5: String
  buildingNumberRange: String
  buildingName: String
  flatName: String
  street: String
  city: String
  county: String
  postalCode: String
  country: String
  uprn: String
  dependentLocality: String
  doubleDependentLocality: String
  typeId: String
}

type EntityStatus {
  locked: Boolean
  confirmed: Boolean
  deactivated: Boolean
}

input Pagination {
  perPage: Int!
  page: Int!
}

type PageInfo {
  number: Int
  size: Int
  totalPages: Int
  totalElements: Int
}

enum BusinessSearchFieldType {
  SBI
  BUSINESS_NAME
  BUSINESS_POSTCODE
}

type BusinessSearchResult {
  organisationId: ID
  sbi: ID
  name: String
  additionalSbis: [ID]
  address: Address
  correspondenceAddress: Address
  isFinancialToBusinessAddress: Boolean
  isCorrespondenceAsBusinessAddress: Boolean
  landConfirmed: Boolean
  lastUpdated: Date
  status: EntityStatus
}

type BusinessSearchResponse {
  results: [BusinessSearchResult]
  pageInfo: PageInfo
}

enum CustomerSearchFieldType {
  CRN
  PERSONAL_IDENTIFIER
  CUSTOMER_NAME
  CUSTOMER_POSTCODE
  VENDOR_NUMBER
  TRADER_NUMBER
}

type CustomerSearchResult {
  personId: ID
  crn: ID
  fullName: String
  address: Address
  personalIdentifiers: [String]
  nationalInsuranceNumber: String
  email: String
  status: EntityStatus
}

type CustomerSearchResponse {
  results: [CustomerSearchResult]
  pageInfo: PageInfo
}

scalar Date

scalar UkAccountNumber

scalar UkSortCode

scalar SwiftCode

type Agreement {
  contractId: ID
  name: String
  status: String
  contractType: String
  schemeYear: Int
  startDate: Date
  endDate: Date
  paymentSchedules: [PaymentSchedule]
}

type PaymentSchedule {
  optionCode: String
  optionDescription: String
  commitmentGroupStartDate: Date
  commitmentGroupEndDate: Date
  year: Int
  sheetName: String
  parcelName: String
  actionArea: Float
  actionMTL: Int
  actionUnits: Float
  parcelTotalArea: Float
  startDate: Date
  endDate: Date
}

type Application {
  sbi: ID!
  id: ID!
  subjectId: ID
  year: Int
  name: String
  moduleCode: String
  scheme: String
  statusCodeP: String
  statusCodeS: String
  status: String
  submissionDate: Date
  portalStatusP: String
  portalStatusS: String
  portalStatus: String
  active: Boolean
  transitionId: ID
  transitionName: String
  agreementReferences: [ID]
  transitionHistory: [Transition]
}

type Transition {
  id: ID
  name: String
  timestamp: Date
  checkStatus: String
}

type BusinessInfo {
  name: String
  reference: String
  vat: String
  traderNumber: String
  vendorNumber: String
  address: Address
  correspondenceAddress: Address
  isCorrespondenceAsBusinessAddress: Boolean
  email: Email
  correspondenceEmail: Email
  phone: Phone
  correspondencePhone: Phone
  legalStatus: BusinessType
  type: BusinessType
  registrationNumbers: BusinessRegistrationNumbers
  additionalSbis: [ID]
  lastUpdated: Date
  isFinancialToBusinessAddress: Boolean
  hasLandInNorthernIreland: Boolean
  hasLandInScotland: Boolean
  hasLandInWales: Boolean
  landConfirmed: Boolean
  hasAdditionalBusinessActivities: Boolean
  additionalBusinessActivities: [BusinessType]
  isAccountablePeopleDeclarationCompleted: Boolean
  dateStartedFarming: Date
  status: EntityStatus
}

type BusinessRegistrationNumbers {
  companiesHouse: String
  charityCommission: String
}

# eslint-disable-next-line @graphql-eslint/naming-convention
type BusinessType {
  code: Int
  type: String
}

type BusinessCustomer {
  personId: ID
  firstName: String
  lastName: String
  crn: String
  role: String
  permissionGroups: [ActivePermissionGroup]
}

type Business {
  organisationId: ID
  sbi: ID!
  info: BusinessInfo
  land: BusinessLand
  countyParishHoldings: [CountyParishHolding]
  customers: [BusinessCustomerPartial]
  customer(crn: ID!): BusinessCustomer
  agreements: [Agreement]
  applications: [Application]
  bankAccounts: [BusinessBankAccount!]
}

type BusinessBankAccount {
  number: String!
  currency: BankAccountCurrency!
}

type BusinessCustomerPartial {
  personId: ID
  firstName: String
  lastName: String
  crn: String
  role: String
}

type CountyParishHolding {
  cphNumber: ID
  parish: String
  startDate: Date
  endDate: Date
  species: String
  xCoordinate: Int
  yCoordinate: Int
  address: String
}

type BusinessLandParcel {
  id: ID!
  sheetId: String
  parcelId: String
  area: Float
  pendingDigitisation: Boolean
  effectiveToDate: Date
  effectiveFromDate: Date
}

type BusinessLandSummary {
  arableLandArea: Float
  permanentCropsArea: Float
  permanentGrasslandArea: Float
  totalArea: Float
  totalParcels: Float
}

type BusinessLandCover {
  id: ID!
  name: String
  area: Float
  code: String
  isBpsEligible: Boolean
}

type BusinessLand {
  parcels(date: Date): [BusinessLandParcelPartial]
  parcel(date: Date, sheetId: ID!, parcelId: ID!): BusinessLandParcel
  parcelCovers(date: Date, sheetId: ID!, parcelId: ID!): [BusinessLandCover]
  parcelLandUses(date: Date, sheetId: ID!, parcelId: ID!): [BusinessLandParcelUses]
  summary(date: Date): BusinessLandSummary
}

type BusinessLandParcelUses {
  code: String!
  startDate: Date
  endDate: Date
  insertDate: Date
  deleteDate: Date
  area: Float
  length: Float
  type: String
  campaign: Int
}

type BusinessLandParcelPartial {
  id: ID!
  sheetId: String
  parcelId: String
  area: Float
  pendingDigitisation: Boolean
}

type CustomerInfo {
  name: CustomerName
  dateOfBirth: Date
  phone: Phone
  email: Email
  status: EntityStatus
  address: Address
  doNotContact: Boolean
  personalIdentifiers: [String]
}

type CustomerName {
  title: String
  otherTitle: String
  first: String
  middle: String
  last: String
}

type CustomerAuthenticationQuestions {
  memorableDate: String
  memorableEvent: String
  memorableLocation: String
  updatedAt: Date
  isFound: Boolean
}

type Customer {
  personId: ID!
  crn: ID!
  info: CustomerInfo
  authenticationQuestions: CustomerAuthenticationQuestions
  businesses: [CustomerBusinessPartial]
  business(sbi: ID!): CustomerBusiness
}

type CustomerBusinessPartial {
  organisationId: ID
  sbi: ID!
  name: String!
  role: String
}

type CustomerBusiness {
  organisationId: ID
  sbi: ID!
  name: String!
  role: String
  messages(fromDate: Date): [CustomerBusinessMessage]
  permissionGroups: [ActivePermissionGroup]
}

type CustomerBusinessMessage {
  id: ID!
  subject: String
  date: Date
  body: String
  read: Boolean
  deleted: Boolean
}

enum PermissionLevel {
  NO_ACCESS
  VIEW
  AMEND
  SUBMIT
  MAKE_LEGAL_CHANGES
  FULL_PERMISSION
}

enum PermissionGroupId {
  BASIC_PAYMENT_SCHEME
  BUSINESS_DETAILS
  COUNTRYSIDE_STEWARDSHIP_AGREEMENTS
  COUNTRYSIDE_STEWARDSHIP_APPLICATIONS
  ENTITLEMENTS
  ENVIRONMENTAL_LAND_MANAGEMENT_APPLICATIONS
  LAND_DETAILS
}

type ActivePermissionGroup {
  id: PermissionGroupId!
  level: PermissionLevel
  functions: [String]
}

type PermissionGroup {
  id: PermissionGroupId!
  name: String!
}

input CreateBusinessCustomerBankDetailsInput {
  sbi: ID!
  crn: ID!
  account: BankAccountInput!
}

input BankAccountInput @oneOf {
  ukBusiness: UkBusinessBankAccountInput
  ukPersonal: UkPersonalBankAccountInput
  ukBusinessBuildingSociety: UkBusinessBuildingSocietyBankAccountInput
  ukPersonalBuildingSociety: UkPersonalBuildingSocietyBankAccountInput
  euBusiness: EuBusinessBankAccountInput
  euPersonal: EuPersonalBankAccountInput
}

input UkBusinessBankAccountInput {
  accountHolderName: String!
  accountNumber: UkAccountNumber!
  bankName: String!
  sortCode: UkSortCode!
  currency: BankAccountCurrency!
}

input UkPersonalBankAccountInput {
  forename: String!
  surname: String!
  accountNumber: UkAccountNumber!
  bankName: String!
  sortCode: UkSortCode!
  currency: BankAccountCurrency!
}

input UkBusinessBuildingSocietyBankAccountInput {
  accountHolderName: String!
  accountNumber: UkAccountNumber!
  rollNumber: String
  bankName: String!
  sortCode: UkSortCode!
  currency: BankAccountCurrency!
}

input UkPersonalBuildingSocietyBankAccountInput {
  forename: String!
  surname: String!
  accountNumber: UkAccountNumber!
  rollNumber: String
  bankName: String!
  sortCode: UkSortCode!
  currency: BankAccountCurrency!
}

input EuBusinessBankAccountInput {
  accountHolderName: String!
  accountNumber: String!
  iban: IBAN!
  countryCode: String!
  bankName: String!
  sortCode: String!
  swiftCode: SwiftCode
  currency: BankAccountCurrency!
}

input EuPersonalBankAccountInput {
  forename: String!
  surname: String!
  accountNumber: String!
  iban: IBAN!
  countryCode: String!
  bankName: String!
  sortCode: String!
  swiftCode: SwiftCode
  currency: BankAccountCurrency!
}

enum BankAccountCurrency {
  GBP
  EUR
}

union CreateBusinessCustomerBankDetailsResult =
  | BankDetailsSubmitted
  | BankDetailsValidationFailed
  | BankDetailsLocked
  | BankDetailsNotEditable

type BankDetailsSubmitted {
  success: Boolean!
}

type BankDetailsValidationFailed {
  message: String!
  attemptsRemaining: Int!
}

type BankDetailsLocked {
  message: String!
}

type BankDetailsNotEditable {
  message: String!
  submitted: Boolean!
  updatedRecently: Boolean!
  new: Boolean!
}

scalar IBAN
