# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  fcp-data-access-layer-api-test-runner:
    build:
      context: .
      target: development
    image: fcp-data-access-layer-api-development
    container_name: fcp-data-access-layer-api-test
    command: npm run test:acceptance
    environment:
      CLIENT_ID: ${fcp-data-access-layer-api-RP-INTERNAL-APIM-CLIENT-ID}
      CLIENT_SECRET: ${fcp-data-access-layer-api-RP-INTERNAL-APIM-CLIENT-SECRET}
      API_TENANT_ID: ${fcp-data-access-layer-api-API-TENANT-ID}
      RP_INTERNAL_APIM_ACCESS_TOKEN_URL: ${fcp-data-access-layer-api-RP-INTERNAL-APIM-ACCESS-TOKEN-URL}
      RP_INTERNAL_HEALTH_CHECK_CUSTOMER_CRN: ${fcp-data-access-layer-api-RP-INTERNAL-HEALTH-CHECK-CUSTOMER-CRN}
      ENTRA_HEALTH_CHECK_USER_OBJECT_ID: ${fcp-data-access-layer-api-ENTRA-HEALTH-CHECK-USER-OBJECT-ID}
      RURAL_PAYMENTS_PORTAL_EMAIL: ${fcp-data-access-layer-api-RURAL-PAYMENTS-PORTAL-EMAIL}
      RP_INTERNAL_HEALTH_CHECK_ORGANISATION_SBI: ${fcp-data-access-layer-api-RP-INTERNAL-HEALTH-CHECK-ORGANISATION-SBI}