services:
  ffc-customer-registry-api:
    build:
      target: development
    image: ffc-customer-registry-api-development
    container_name: ffc-customer-registry-api-test
    command: npm run test:local
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./package.json:/home/node/package.json
    environment:
      ENABLE_MOCK_SERVER: true
      PORT_MOCK: 3100
      RURAL_PAYMENTS_AGENCY_LAND_API_URL: https://environment.data.gov.uk
      RURAL_PAYMENTS_PORTAL_API_URL: http://localhost:3100/rpp/
      RURAL_PAYMENTS_PORTAL_EMAIL: some-email
