name: fcp-data-access-layer-api
namespace: ffc-dal
image: fcp-data-access-layer-api

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80

service:
  port: 80
  type: ClusterIP
  
container:
  port: 3000
  memCpuTier: CUSTOM
  imagePullPolicy: IfNotPresent
  requestMemory: 50Mi
  requestCpu: 50m
  limitMemory: 200Mi
  limitCpu: 400m
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000

ingress:
  class: nginx
  endpoint: ffc-dal
  server: example.com

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-dal
  roleArn: true
