name: fcp-data-access-layer-api
namespace: ffc-dal
image: fcp-data-access-layer-api

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5

container:
  port: 3000
  memCpuTier: M

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
