input UpdateBusinessInput {
  """
  SBI (Single Business Identifier) of the business that is being updated.
  """
  sbi: ID!

  """
  Business details to be updated.
  """
  details: InputBusinessDetails!
}

input InputBusinessDetails {
  """
  Name of the business.
  """
  name: String

  """
  Address of the business.
  """
  address: InputAddress

  """
  Correspondence Address of the business.
  """
  correspondenceAddress: InputAddress

  """
  Indicates whether the correspondence address is the same as the business address.
  """
  isCorrespondenceAsBusinessAddress: Boolean
  """
  Telephone number of the business.
  """
  phone: InputPhone

  """
  Correspondence telephone number of the business.
  """
  correspondencePhone: InputPhone

  """
  Email address of the business.
  """
  email: InputEmail
  """
  Correspondence email address of the business.
  """
  correspondenceEmail: InputEmail
}
