input UpdateBusinessDetailsInput {
  """
  SBI (Single Business Identifier) of the business that is being updated.
  """
  sbi: ID!

  """
  Business details to be updated.
  """
  details: InputBusinessDetails!
}

input InputBusinessDetails {
  """
  Name of the business.
  """
  name: String!

  """
  Firm Reference Number (FRN) of the business.
  """
  reference: String

  """
  VAT number of the business.
  """
  vat: String

  """
  Trader number of the business.
  """
  traderNumber: String

  """
  Vendor number of the business.
  """
  vendorNumber: String

  """
  Address of the business.
  """
  address: InputAddress!

  """
  Correspondence Address of the business.
  """
  correspondenceAddress: InputAddress

  """
  Indicates whether the correspondence address is the same as the business address.
  """
  isCorrespondenceAsBusinessAddr: Boolean
  """
  Telephone number of the business.
  """
  phone: InputPhone!

  """
  Correspondence telephone number of the business.
  """
  correspondencePhone: InputPhone

  """
  Email address of the business.
  """
  email: InputEmail!
  """
  Correspondence email address of the business.
  """
  correspondenceEmail: InputEmail
  """
  Type of the business represented by a code/description pair. For example, used for business type and legal status.
  """
  type: InputBusinessType!
}

"""
Input type for the business represented by a code/description pair. For example, used for business type and legal status.
""" # eslint-disable-next-line @graphql-eslint/naming-convention
input InputBusinessType {
  """
  Code of the business type.
  """
  code: Int

  """
  Description of the business type.
  """
  type: String
}
