extend type Mutation {
  updateBusinessDetails(sbi: ID!, businessDetails: InputBusinessDetails): Business @on
  updateBusinessAdditionalDetails(sbi: ID!, businessDetails: InputBusinessDetails): Business @on
}
