extend type Business {
  payments(fromDate: Date, toDate: Date, userIP: String!): BusinessPayments
    @on
    @auth(requires: [CONSOLIDATED_VIEW])
}

type BusinessPayments {
  onHold: Boolean!
  payments: [Payment!]!
}

type Payment {
  reference: String!
  date: Date!
  amount: Float!
  currency: String!
  lineItems: [PaymentLineItem!]!
}

type PaymentLineItem {
  agreementClaimNo: String!
  scheme: String!
  marketingYear: String!
  description: String!
  amount: Float!
}
