{{- include "ffc-helm-library.container-secret" (list . "ffc-customer-registry-api.container-secret") -}}
{{- define "ffc-customer-registry-api.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  RURAL_PAYMENTS_PORTAL_EMAIL: {{ quote .Values.dataSources.ruralPaymentsPortalEmail }}
  {{- end }}
{{- end -}}
