#!/bin/sh
git fetch --tags --quiet

if ! command -v jq > /dev/null 2>&1; then
  echo "ERROR: jq is required but not installed (so that package json version bump can be verified). See https://jqlang.org/download/"
  exit 1
fi

# Use the highest existing repo-wide tag rather than main's package.json, since hotfix branches can tag a version higher than the latest main version
TARGET_VERSION=$(git tag -l | xargs npx -y semver | tail -n1)
LOCAL_VERSION=$(jq -r '.version' ./package.json)

if ! npx -y semver -r ">${TARGET_VERSION}" "${LOCAL_VERSION}" > /dev/null 2>&1 ; then
  echo "ERROR: Branch package.json version (${LOCAL_VERSION}) must be semantically greater than the highest existing repository tag (${TARGET_VERSION})"
  exit 1
fi

