name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install and audit
        run: |
          npm audit --omit=dev
          npm ci

      - name: Lint code
        run: npm run lint

      - name: Jest Coverage Comment
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test

      - name: Local dev check
        env:
          NODE_OPTIONS: --experimental-vm-modules
        run: |
          docker compose up --quiet-pull --build -d
          set +e
          npm i graphql-request
          curl -s --max-time 10 --retry 5 --retry-delay 1 --retry-all-errors http://localhost:3000/health
          npx jest --coverage false test/acceptance/local-dev-check.test.js
          RESULT=$?
          docker compose down --remove-orphans
          set -e
          exit $RESULT

      - name: Sonarqube Cloud Scan
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
