name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup npm and audit
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: |
          npm audit --omit=dev
          npm ci

      - name: Jest Coverage Comment
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag fcp-dal-api .
          exit $?

      - name: Sonarqube Cloud Scan
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
